name: "Create built versions cache"
on:
  pull_request:
  push:
  schedule:
    - cron: '15 * * * *'

jobs:
  unstable_x86_64-linux:
    uses: ./.github/workflows/workflow.yml
    with:
      flake_ref: github:flox/nixpkgs/unstable
      attr_path: legacyPackages.x86_64-linux
      git_token: ${{ secrets.GIT_TOKEN }}


  stable_x86_64-linux:
    uses: ./.github/workflows/workflow.yml
    with:
      flake_ref: github:flox/nixpkgs/stable
      attr_path: legacyPackages.x86_64-linux
      git_token: ${{ secrets.GIT_TOKEN }}



  staging_x86_64-linux:
    uses: ./.github/workflows/workflow.yml
    with:
      flake_ref: github:flox/nixpkgs/staging
      attr_path: legacyPackages.x86_64-linux
      git_token: ${{ secrets.GIT_TOKEN }}




  unstable_aarch64-darwin:
    uses: ./.github/workflows/workflow.yml
    with:
      flake_ref: github:flox/nixpkgs/unstable
      attr_path: legacyPackages.aarch64-darwin
      git_token: ${{ secrets.GIT_TOKEN }}


  stable_aarch64-darwin:
    uses: ./.github/workflows/workflow.yml
    with:
      flake_ref: github:flox/nixpkgs/stable
      attr_path: legacyPackages.aarch64-darwin



  staging_aarch64-darwin:
    uses: ./.github/workflows/workflow.yml
    with:
      flake_ref: github:flox/nixpkgs/staging
      attr_path: legacyPackages.aarch64-darwin
      git_token: ${{ secrets.GIT_TOKEN }}



