name: "Create built versions cache"
on:
  workflow_call:
jobs:
  unstable_x86_64-linux:
    uses: ./.github/workflows/workflow.yml
    with:
      flake_ref: github:flox/nixpkgs/unstable
      attr_path: legacyPackages.x86_64-linux
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  stable_x86_64-linux:
    uses: ./.github/workflows/workflow.yml
    with:
      flake_ref: github:flox/nixpkgs/stable
      attr_path: legacyPackages.x86_64-linux
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  staging_x86_64-linux:
    uses: ./.github/workflows/workflow.yml
    with:
      flake_ref: github:flox/nixpkgs/staging
      attr_path: legacyPackages.x86_64-linux
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  unstable_aarch64-darwin:
    uses: ./.github/workflows/workflow.yml
    with:
      flake_ref: github:flox/nixpkgs/unstable
      attr_path: legacyPackages.aarch64-darwin
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  stable_aarch64-darwin:
    uses: ./.github/workflows/workflow.yml
    with:
      flake_ref: github:flox/nixpkgs/stable
      attr_path: legacyPackages.aarch64-darwin
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  staging_aarch64-darwin:
    uses: ./.github/workflows/workflow.yml
    with:
      flake_ref: github:flox/nixpkgs/staging
      attr_path: legacyPackages.aarch64-darwin
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
