name: "Create built versions cache"
on:
  workflow_call:
    inputs:
      flake_ref:
        description: "Target flakeref"
        required: true
        type: string
        default: .
      attr_path:
        description: "Target attr_path"
        required: true
        type: string
        default: "legacyPackages.x86_64-linux"
      aws_bucket:
        description: "AWS S3 Bucket"
        required: false
        type: string
        default: "versions-cache"
      secrets:
        git_token: ${{ secrets.GIT_TOKEN }}

jobs:
  eval_cache:
    runs-on: ubuntu-latest
    concurrency: ${{ github.ref}}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: flox/flox-integration-action@master
        with:
          flake_ref: ${{inputs.flake_ref}}
          attr_path: ${{inputs.attr_path}}
          substituter: https://storehouse.beta.floxdev.com/project/flox-examples
          aws_bucket: ${{inputs.aws_bucket}}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          git_token: ${{ secrets.GIT_TOKEN }}
